# site name
siteName: kx-zyq
shortName: KX

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    极客: {path: /categories/技术/, fa: fa-terminal }, 
    文章: {path: /categories/生活/, fa: fa-file-text-o }, 
    影评: {path: /archives, fa: fa-quote-right }, 
    随想: {path: /archives, fa: fa-commenting-o },
    笔记: {path: /archives, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /archives, fa: fa-th-list faa-bounce }, 
    番组: {path: /archives, fa: fa-film faa-vertical }, 
    歌单: {path: /archives, fa: fa-headphones }
  } }
  留言板: { path: /, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links, fa: fa-link faa-shake }
  赞赏: { path: /, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /archives, fa: fa-meetup}, 
    统计: {path: /archives, fa: fa-area-chart }, 
    监控: {path: /archives, fa: fa-heartbeat },
    主题: {path: /archives, fa: iconfont icon-sakura },
    索引: {path: /archives, fa: fa-map-signs }
  } }
  客户端: { path: /, fa: fa-android faa-vertical }
  RSS: { path: /, fa: fa-rss faa-pulse }

archives:
  技术: /tech || fa-terminal
  生活: /live || fa-file-text-o

# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon and site master avatar
favicon: 
avatar: 

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or founded date
siteBuildingTime: 07/17/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
# menu:
#    技术: tech
#    生活: live
   # 资源: resource


# cover info config
coverTitle: 
coverDescription: XXX的博客
sinaWb: 
facebook: 
qq: 
github: 


# Git-pages server info
gitPageServerName: Github Pages
gitPageServerUrl: https://github.com/
codingPageServerName: Coding Pages
codingPageServerUrl: https://pages.coding.me