# site name
siteName: さくら荘その
shortName: hojun
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://wx1.sinaimg.cn/large/006bYVyvgy1ftand2qurdj303c03cdfv.jpg
url: https://sakura.hojun.cn
description: 好少年光芒万丈

notice: hexo-Sakura主题已经开源，目前正在开发中...

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /video, fa: fa-film faa-vertical }, 
    歌单: {path: /music, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links, fa: fa-link faa-shake }
  赞赏: { path: /donate, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about, fa: fa-meetup}, 
    主题: {path: /theme-sakura, fa: iconfont icon-sakura },
    Lab: {path: /lab, fa: fa-cogs },
  } }
  客户端: { path: /client, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false



# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片
bgn: 8

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.3.2/img/other/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.6/img/other/th%20(3).jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: https://wx3.sinaimg.cn/mw690/006bYVyvly1fz32wrs8d2j30zk0m8wu5.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018


# cover info config
coverTitle: 
coverDescription: XXX的博客

#social  url, img PC端配置
social:
  github: {url: http://github.com/honjun, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/github.png}
  sina: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/sina.png}
  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/wangyiyun.png}
  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/zhihu.png}
  email: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/moezx/cdn@3.1.9/img/Sakura/images/sns/email.svg}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}




# Git-pages server info
gitPageServerName: Github Pages
gitPageServerUrl: https://github.com/
codingPageServerName: Coding Pages
codingPageServerUrl: https://pages.coding.me